argument0=string_replace_all(argument0,"omwam_","");
argument0=string_replace_all(argument0,".ini","");
argument0=string_replace_all(argument0,".","");
argument0=string_lettersdigits(argument0);
if(string_length(argument0)>2 and revision("omwam_"+argument0+".ini")){
    with(adorno){
        depth=collision_circle(x,y,radiobjeto,baldosa,1,1);
        if(depth>0){
            if(depth.tipo>0){
                instance_destroy();}}
        depth=y*-10;}
    with(natural){
        depth=collision_circle(x,y,radiobjeto,baldosa,1,1);
        if(depth>0){
            if(depth.tipo>0){
                instance_destroy();}}
        depth=y*-10;}
    with(cultivo){
        depth=collision_circle(x,y,radiobjeto,baldosa,1,1);
        if(depth>0){
            if(depth.tipo>0){
                instance_destroy();}}
        depth=y*-10;}
    with(baldosa){
        if(tipo=0){
            if(collision_point(x,y,bloque,1,1)){
                if(!collision_point(x,y,natural,1,1)){
                    instance_destroy();}}}}
    ini_open("omwam_"+argument0+".ini");
    ini_section_delete("config");
    ini_section_delete("objeto");
    ini_section_delete("baldosa");
    ini_section_delete("natural");
    ini_section_delete("adorno");
    ini_section_delete("casa");
    ini_section_delete("muro1");
    ini_section_delete("muro2");
    ini_section_delete("muro3");
    ini_section_delete("viducha");
    ini_section_delete("cultivo");
    ini_section_delete("enemigo");
    ini_section_delete("guardian");
    ini_section_delete("campesino");
    ini_section_delete("capturado");
    ini_section_delete("player");
    ini_section_delete("creaenemigos");
    ini_section_delete("creaguardianes");
    ini_section_delete("creamuniciones");
    ini_section_delete("creavidas");
    ini_section_delete("checkpoint");
    ini_write_string("config","ancho",string(room_width));
    ini_write_string("config","alto",string(room_height));
    ini_write_string("config","puertax",string(condicionador.x));
    ini_write_string("config","puertay",string(condicionador.y));
    ini_write_string("config","tiempo",string(condicionador.tiempo));
    ini_write_string("config","cazados",string(condicionador.cazados));
    ini_write_string("config","renovaenemigos",string(condicionador.renovaenemigos));
    ini_write_string("config","renovaguardianes",string(condicionador.renovaguardianes));
    ini_write_string("config","densidadenemigos",string(condicionador.densidadenemigos));
    ini_write_string("config","densidadguardianes",string(condicionador.densidadguardianes));
    ini_write_string("config","relojenemigos",string(condicionador.relojenemigos));
    ini_write_string("config","relojguardianes",string(condicionador.relojguardianes));
    ini_write_string("config","rescatenemigos",string(condicionador.rescatenemigos));
    ini_write_string("config","rescateguardianes",string(condicionador.rescateguardianes));
    ini_write_string("config","relojmunicion",string(condicionador.relojmunicion));
    ini_write_string("config","relojvidas",string(condicionador.relojvidas));
    ini_write_string("config","municionplayer",string(condicionador.municionplayer));
    for(i=0;i<instance_number(objeto);i+=1){
        aux=instance_find(objeto,i);
        ini_write_string("objeto","x"+string(i),string(aux.x));
        ini_write_string("objeto","y"+string(i),string(aux.y));
        ini_write_string("objeto","t"+string(i),string(aux.tipo));
        ini_write_string("objeto","m"+string(i),string(aux.municion));}
    for(i=0;i<instance_number(baldosa);i+=1){
        aux=instance_find(baldosa,i);
        ini_write_string("baldosa","x"+string(i),string(aux.x));
        ini_write_string("baldosa","y"+string(i),string(aux.y));
        ini_write_string("baldosa","t"+string(i),string(aux.tipo));}
    for(i=0;i<instance_number(natural);i+=1){
        aux=instance_find(natural,i);
        ini_write_string("natural","x"+string(i),string(aux.x));
        ini_write_string("natural","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(casa);i+=1){
        aux=instance_find(casa,i);
        ini_write_string("casa","x"+string(i),string(aux.x));
        ini_write_string("casa","y"+string(i),string(aux.y));
        ini_write_string("casa","t"+string(i),string(aux.tipo));}
    for(i=0;i<instance_number(muro1);i+=1){
        aux=instance_find(muro1,i);
        ini_write_string("muro1","x"+string(i),string(aux.x));
        ini_write_string("muro1","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(muro2);i+=1){
        aux=instance_find(muro2,i);
        ini_write_string("muro2","x"+string(i),string(aux.x));
        ini_write_string("muro2","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(muro3);i+=1){
        aux=instance_find(muro3,i);
        ini_write_string("muro3","x"+string(i),string(aux.x));
        ini_write_string("muro3","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(adorno);i+=1){
        aux=instance_find(adorno,i);
        ini_write_string("adorno","x"+string(i),string(aux.x));
        ini_write_string("adorno","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(cultivo);i+=1){
        aux=instance_find(cultivo,i);
        ini_write_string("cultivo","x"+string(i),string(aux.x));
        ini_write_string("cultivo","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(viducha);i+=1){
        aux=instance_find(viducha,i);
        ini_write_string("viducha","x"+string(i),string(aux.x));
        ini_write_string("viducha","y"+string(i),string(aux.y));
        ini_write_string("viducha","t"+string(i),string(aux.tipo));}
    for(i=0;i<instance_number(cosoenemigo);i+=1){
        aux=instance_find(cosoenemigo,i);
        ini_write_string("enemigo","x"+string(i),string(aux.x));
        ini_write_string("enemigo","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(cosoguardian);i+=1){
        aux=instance_find(cosoguardian,i);
        ini_write_string("guardian","x"+string(i),string(aux.x));
        ini_write_string("guardian","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(cosocampesino);i+=1){
        aux=instance_find(cosocampesino,i);
        ini_write_string("campesino","x"+string(i),string(aux.x));
        ini_write_string("campesino","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(capturado);i+=1){
        aux=instance_find(capturado,i);
        ini_write_string("capturado","x"+string(i),string(aux.x));
        ini_write_string("capturado","y"+string(i),string(aux.y));}
    for(i=0;i<instance_number(creaenemigos);i+=1){
        aux=instance_find(creaenemigos,i);
        ini_write_string("creaenemigos","x"+string(i),string(aux.x));
        ini_write_string("creaenemigos","y"+string(i),string(aux.y));
        ini_write_string("creaenemigos","t"+string(i),string(aux.arma));
        ini_write_string("creaenemigos","a"+string(i),string(aux.area));}
    for(i=0;i<instance_number(creaguardianes);i+=1){
        aux=instance_find(creaguardianes,i);
        ini_write_string("creaguardianes","x"+string(i),string(aux.x));
        ini_write_string("creaguardianes","y"+string(i),string(aux.y));
        ini_write_string("creaguardianes","t"+string(i),string(aux.arma));
        ini_write_string("creaguardianes","a"+string(i),string(aux.area));}
    for(i=0;i<instance_number(creamuniciones);i+=1){
        aux=instance_find(creamuniciones,i);
        ini_write_string("creamuniciones","x"+string(i),string(aux.x));
        ini_write_string("creamuniciones","y"+string(i),string(aux.y));
        ini_write_string("creamuniciones","t"+string(i),string(aux.arma));
        ini_write_string("creamuniciones","a"+string(i),string(aux.area));}
    for(i=0;i<instance_number(creavidas);i+=1){
        aux=instance_find(creavidas,i);
        ini_write_string("creavidas","x"+string(i),string(aux.x));
        ini_write_string("creavidas","y"+string(i),string(aux.y));
        ini_write_string("creavidas","t"+string(i),string(aux.tipo));
        ini_write_string("creavidas","a"+string(i),string(aux.area));}
    for(i=0;i<instance_number(checkpoint);i+=1){
        aux=instance_find(checkpoint,i);
        ini_write_string("checkpoint","x"+string(i),string(aux.x));
        ini_write_string("checkpoint","y"+string(i),string(aux.y));}
    if(instance_exists(cosoplayer)){
        ini_write_string("player","x",string(cosoplayer.x));
        ini_write_string("player","y",string(cosoplayer.y));
        if(cosoplayer.vidas>0){
            ini_write_string("config","vidas",string(cosoplayer.vidas));}
        else{
            ini_write_string("config","vidas","-1");}}
    else{
        ini_write_string("config","vidas","-2");}
    ini_close();
    validandolo(argument0);
    ini_open("config_omwa.ini");
    ini_write_string("mapas",argument0,"2");
    ini_write_string("config","ultimo",argument0);
    if(os_type!=os_windows){
        ini_write_string("config","mapalinux",argument0);}
    ini_close();
    audio_play_sound(s_guardar,8,0);
    instance_create(0,0,succesfull);}
